/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pila_Pila */

#ifndef _Included_pila_Pila
#define _Included_pila_Pila
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
